#!/bin/bash
# ================s===================================
# Install docker engine with TLS for remote api access
# ===================================================
#

echo "
======================================
Install docker engine
======================================"

# Uninstall old versions
apt-get remove docker docker-engine docker.io containerd runc

# Install requirement
apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

# include configure.sh generated by makefile (make vm-init)
. /vagrant/.download/configure.sh

# Install from package .deb
dpkg -i $PKG_FILEPATH_DOCKER_CE_CLI
dpkg -i $PKG_FILEPATH_CONTAINERD
dpkg -i $PKG_FILEPATH_DOCKER_CE
docker --version

# Install docker-compose
COMPOSE_DEST=/usr/local/bin/docker-compose
cp $PKG_FILEPATH_COMPOSE $COMPOSE_DEST
chmod +x /usr/local/bin/docker-compose
docker-compose --version

# Active swarm
NET_DEFAULT=enp0s8
docker swarm init --advertise-addr $NET_DEFAULT


